# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 864b456f8cfb8a20201b10bbea04fd7c9fd980aa27b6a99cef761207d8b8012e056bb1740082b2b703f65057fe5f0f7ff8757744bcaf689b63c2e671fbc77f46

test:
  secret_key_base: 30da02cd869dd73c060e4022f605fade8a1e8360e08d1a869a523ba2639dcb5b5b442039b3bdb875604af65dddeb3cb735f82bfcde574ec245406ab97b9b7584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
